### ISSUE TITLE
GPU 9999: invalid device ordinal

### ISSUE THREAD

**Issue by philippegabert** [xmrMiner/xmrMiner#16]
Hello, 

when I try to start the miner, I get this error.
I've tried with one machine with one Tesla K80 and it worked. 
This test is with multiple K80. (I've tried to add the flag "-d" with values "0" or "0,1" but same issue.

Thanks

Philippe

```
ubuntu@ip-172-31-11-126:~/xmrMiner$ ./xmrMiner -o stratum+tcp://xmr.crypto-pool.fr:3333 -u 41yXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK -p x --launch=24x39
    *** xmrMiner 0.2.1 (64 bit) for NVIDIA GPUs by psychocrypt
    *** Built with GCC 5.4  using the Nvidia CUDA Toolkit 8.0

 psychocrypt's XMR donation address:
   43NoJVEXo21hGZ6tDG6Z3g4qimiGdJPE6GRxAmiWwm26gwr62Lqo7zRiCJFSBmbkwTGNuuES9ES5TgaVHceuYc4Y75txCTU
 for more donation addresses please read the README.md
-----------------------------------------------------------------

GPU 9999: invalid device ordinal
/home/ubuntu/xmrMinerProject/xmrMiner/cryptonight/cryptonight.cu line 75
```

**Comment by psychocrypt** [comment]
Could you please try the miner [xmr-stak-nvidia](https://github.com/fireice-uk/xmr-stak-nvidia) if this error is there also shown?

**Comment by philippegabert** [comment]
Hi, 

it seem to work just fine. (But with awful results)

Philippe

**Comment by psychocrypt** [comment]
Then please move to xmr-stak. I am currently updating xmr-stak to have the same hashrates than xmrMiner.

**Comment by psychocrypt** [comment]
not re produce able (user switched to xmr-stak-nvidia :+1: )

**Comment by BrockChen** [comment]
@philippegabert your GPU nums must less than 8
