### ISSUE TITLE
Malware?

### ISSUE THREAD

**Issue by R0byn** [xmrMiner/xmrMiner#18]
virus-scanned xmrMiner-Win64-master.zip (0.2.1).
Avast Free Antivirus says "Win64:Malware-gen" and
Detection ratio:	6 / 59 at virustotal:
https://www.virustotal.com/en/file/17fd32cb89017e91d720a341d71ff2ce2f948c81d3ebae2e527d181da8b02939/analysis/1493406240/

**Comment by psychocrypt** [comment]
I think this is an issue with all monero miner. If you are not sure or trust the pre compiled binaries the most secure way is to compile a binary out of the source.

**Comment by psychocrypt** [comment]
This was a wrong alert from some vendors, know all is fine https://www.virustotal.com/en/url/cf42f4efd3f7b2d40def102926561835f9307827fdf4bb2acdf68de8cb7a13c3/analysis/1495825515/
