### ISSUE TITLE
need recommendation for tesla p100

### ISSUE THREAD

**Issue by renderit** [xmrMiner/xmrMiner#29]
Hey great work here! Sort of beginner with this. Quick question regarding choosing the parameter for the `launch-parameter`. I have **8 tesla GPU**. To be precise, `Tesla P100-SXM2-16GB` **16 GB** .. what are your recommendation for putting the `launch parameter` for this? I see in the table you mentioned `72 * 56` I wanted to know if this would change with the number of GPU's? or should i stick with `72 * 56`.
Cheers

**Comment by psychocrypt** [comment]
sry for the late answer: 72x56 is a good setting for the P100.
