### ISSUE TITLE
Not working for nvidia Cuda V9.0

### ISSUE THREAD

**Issue by torreta** [xmrMiner/xmrMiner#34]

**Comment by neocruiser** [comment]
Same thing. Problem with cudart64_80.dll
There is only cudart64_90.dll under programfiles/cuda

Copy/pasted the _90.dll into xmr folder. Then renamed it with _80.dll
The xmrMiner_easyStart.bat loads only to issue the pause statement

edit: i replaced the cudart64_80.dll with the one from https://github.com/fireice-uk/xmr-stak-nvidia/releases
it works

**Comment by psychocrypt** [comment]
please use xmr-stak: https://github.com/fireice-uk/xmr-stak/releases
