### ISSUE TITLE
How do you set launch conf for 2 different cards? 

### ISSUE THREAD

**Issue by auroracoin** [xmrMiner/xmrMiner#35]
How do you set launch conf for 2 different cards?  -d 0 -l 8x30  -d 1 -l 6x24   ect?  -d doesn't work. And bFactor=10-b  for -d 0 and bFactor=2 for -d 1

**Comment by r0bdav** [comment]
Hi, I've also struggled using different iterations to get two different cards to work. Could someone perhaps help with the correct mechanics to setup two cards with different configs ideally using the easystart file? (brand new at this!)

**Comment by aaronmboyd** [comment]
@r0bdav @auroracoin I set up a Docker image to encapsulate xmrMiner here: https://github.com/aaronmboyd/docker-xmrMiner

It utilises NVIDIA's own Docker-wrapper program [nvidia-docker](https://github.com/NVIDIA/nvidia-docker). As an added benefit of this, you can run the container multiple times for different graphics cards with different launch parameters, as I mention in the readme:

#### Example run command isolating the first GPU only ###
```
  NV_GPU=0 nvidia-docker run aaronmboyd/xmrminer --url=stratum+tcp://mine.xmrpool.net:5555 --launch=10x24 --bfactor=4 --bsleep=100 --user=44NxHdzAJPVZkfXGnRd7kiGc1xCrg3GPncMwECKCmfbXRhVqhTreT7a2DGWcwCD3f7FnDsu1eCYusaTJoaETPajD3dPTdpQ -p docker_worker_1 --donate=1
```

**Comment by r0bdav** [comment]
Thanks, will check it out in the next day or so!

**Comment by auroracoin** [comment]
Thank you... one thing please... --bsleep=100... I don't understand what setting I should put this at. And if it has any effect on hashrate. Right now I'm using --bsleep 25.  Thx
Ps using windows 8.1 
That docker is for lunix.

**Comment by aaronmboyd** [comment]
Oh right, yeah that Docker image is for linux only at this point. Regardless, I am not the author of xmrMiner and don't really know precisely what the `bsleep` setting does - I just posted an example usage above.

Also, I think this project is not really supported anymore, and [xmr-stak-nvidia](https://github.com/fireice-uk/xmr-stak-nvidia) is a more up to date NVIDIA miner? @psychocrypt could confirm this.

**Comment by psychocrypt** [comment]
Use the launch option with a comma separated list `--launch="TxB,TxB"`

Yes xmrMiner is not improved any more. Please use xmr-stak.

**Comment by aaronmboyd** [comment]
Haha that's way easier, awesome.

**Comment by auroracoin** [comment]
Thx `--launch="TxB,TxB"` works. But also needed bFactor set too. Like bFactor=10,2 
Ok looking at xmr-stak now. Thx

xmr-stak is way to difficult. Could you have an example conf file and how to exacute it plz :-)

**Comment by psychocrypt** [comment]
new release for xmr-stak: https://github.com/fireice-uk/xmr-stak/releases
