### ISSUE TITLE
daemon connection causing errors

### ISSUE THREAD

**Issue by zahgerman** [xmrMiner/xmrMiner#36]
Attempting to use in solo mining. Unable to get the configuration to work.

starting with the option "-o daemon+tcp://0.0.0.0:port/json_rpc" does not start mining

using the option "-o stratum+tcp://0.0.0.0:port/json_rpc" causes the following error in the daemon: 
<date> [RPC0]  ERROR   net.http        contrib/epee/include/net/http_protocol_handler.inl:357  simple_http_connection_handler<t_connection_context>::handle_invoke_query_line(): Failed to match first line: {"method": "login", "params": {"login": "################", "pass": "x", "agent": "xmrMiner/0.2.1"}, "id": 1}

**Comment by psychocrypt** [comment]
please switch to the miner xmr-stak to solve this issue: https://github.com/fireice-uk/xmr-stak/releases
