### ISSUE TITLE
Connection Timed Out

### ISSUE THREAD

**Issue by vitorgamer58** [xmrMiner/xmrMiner#40]
Connection Timed Out
this problem is only appearing in XMRMINER, it does not happen with XMRIG.
![Connection Timed Out](http://ap.imagensbrasil.org/images/2018/02/13/Screenshot_337.png)

**Comment by psychocrypt** [comment]
This is an issue with you web connection. Do you use WiFi? You could try if you can ping the pool.
If you still have issues please switch to [xmr-stak](https://github.com/fireice-uk/xmr-stak/releases)

**Comment by vitorgamer58** [comment]
but with Xmrig does not give this problem, and I'm dealing with different pools, I do not use WiFi, just cable.

**Comment by psychocrypt** [comment]
Than the best is to switch to xmr-stak. Xmr-stak supports nvidia, amd and
cpu mining within one miner.

**Comment by vitorgamer58** [comment]
Ok :)
