### ISSUE TITLE
Support for hardfork on April 6?

### ISSUE THREAD

**Issue by holitics** [xmrMiner/xmrMiner#41]
Is there any plan on adding support for the upcoming fork for this miner? 

Thank you.

**Comment by psychocrypt** [comment]
The last release already contains monero v7 POW changes.

**Comment by holitics** [comment]
Sorry, I didnt know about the xmrStak codebase when I made this post. I am
now using that code.

**Comment by phubbard91** [comment]
Sorry if this is a stupid question; how is this ready for the v7 fork if the last commit was a year ago? Thanks for all your hard work.

**Comment by holitics** [comment]
I think psychocrypt was referring to xmrStak unified miner, found here: https://github.com/fireice-uk/xmr-stak. Someone should document the move on the main project page though, I wasted several hours compiling this code initially.

**Comment by psychocrypt** [comment]
Ohh no sry I answered via mail and thought it was a question in xmr-stak.
Never the less I will implement pow7 into this miner in the next days
before the fork.
You can also use  xmr-stak.

**Comment by psychocrypt** [comment]
PR for POW v7 is open #42, will be merged soon

**Comment by holitics** [comment]
thanks!

**Comment by psychocrypt** [comment]
support is now merged and in the master. I am currently compile the binaries
